language: node_js
node_js:
- '0.11'
- '0.10'
services:
- mongodb
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
  sudo tee /etc/apt/sources.list.d/mongodb.list
- sudo apt-get update
- sudo apt-get install mongodb-org-server
before_script:
- until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
deploy:
  provider: npm
  email: abdi.dahir@outlook.com
  api_key:
    secure: G0TqAmwGj4gIglLpdkbEbRsZAzq1sKDB6ia/pZJMK/2ZxAaILjKORsNKROYRqYe4YVevO8OmBKEQ9NKzTtI5ToMcJZNtqrsgxawXUW105Sm/rJ0uRM4TwGrR7R3+YICxQzex6Rp6G9wJCRNeBa9AurbEYY0r0iXfdMWG6wHGHHU=
  on:
    tags: true
    all_branches: true
    repo: Snkz/mongoose-rollback
